### ISSUE TITLE
Include Labels when pushing descriptions to superset

### ISSUE THREAD

**Issue by aibunny** [slidoapp/dbt-superset-lineage#40]
I have noticed that only column descriptions are pushed to superset, I think it would be great if also Labels were included.

**Comment by one-data-cookie** [comment]
Thanks for the idea, @aibunny!

How would you imagine to store these in dbt YAML files so that they could be transferred to Superset? The only thing that comes to mind is under `meta.label`, or?

**Comment by aibunny** [comment]
My initial thoughts was to have them like below  but also in the `meta.label` would still work.
```models:
  - name: Blah blah
    description: blah data mart
  columns:
      - name: column1
      description: column1 desc
      label: Column 1
```

**Comment by one-data-cookie** [comment]
Well, that wouldn't throw you an error but it wouldn't show up in dbt Docs. Only `meta.label` does.

```yaml
columns:
  - name: account_uuid
    description: '{{ doc("account_uuid") }}'
    label: "this-is-very-interesting"
    meta:
      label: "this-is-even-more-interesting"
      dog: "cat"
```

<img width="337" alt="image" src="https://github.com/slidoapp/dbt-superset-lineage/assets/57877739/fb8bfc09-af3e-4815-90a7-8c232a1ce700">

As you can see though, the issue is that you can put literally anything into `meta` so this is not really a standardised thing and I'm not sure whether anyone actually uses it like this.
