### ISSUE TITLE
Feature request: Append create Superset chart URL in dbt model description

### ISSUE THREAD

**Issue by rohitsanj** [slidoapp/dbt-superset-lineage#43]
In an effort to ease user flow from dbt docs into Superset, we could programmatically append a markdown hyperlink into a dbt model's `description`, pointing to the "create chart" page in Superset. 

For example, consider the following file, `orders.yml`
```yaml
# orders.yml
models:
  - name: orders
    description: |
      This table has basic information about orders, as well as some derived facts based on payments

      [Explore this table!](http://localhost:8088/explore/?datasource_type=table&datasource_id=97)
    columns: ...
```

dbt docs page:
![Screenshot 2024-02-21 at 4 21 00 PM](https://github.com/slidoapp/dbt-superset-lineage/assets/39169550/f4abfb6c-da2e-4a86-acb0-46b428d1c9c7)

Clicking "Explore this table!" takes you to this Superset page:

<img width="1656" alt="Screenshot 2024-02-21 at 4 44 54 PM" src="https://github.com/slidoapp/dbt-superset-lineage/assets/39169550/d501de31-699d-4166-a760-c2040dccd5b4">
